unit uTestuDrawingCommand;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uExceptions, Graphics, uBaseCommand, uDrawingCommand, uBase,
  uGraphicPrimitive, Variants;

type
  // Test methods for class TBaseDrawingCommand

  TestTBaseDrawingCommand = class(TTestCase)
  strict private
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestDrawingCommandFactory;
  end;
  // Test methods for class TChangeBackgroundColorCommand

  TestTChangeBackgroundColorCommand = class(TTestCase)
  strict private
    FChangeBackgroundColorCommand: TChangeBackgroundColorCommand;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestExecute;
  end;

implementation

procedure TestTBaseDrawingCommand.SetUp;
begin
//
end;

procedure TestTBaseDrawingCommand.TearDown;
begin
//
end;

procedure TestTBaseDrawingCommand.TestDrawingCommandFactory;
var
  Prim : TBaseDrawingCommand;
  i : TDrawingCommandType;
begin
  for I := Low( TDrawingCommandType ) to High( TDrawingCommandType ) do begin
    Prim := DrawingCommandFactory( I );
    Check( Prim <> nil );
  end;
end;

procedure TestTChangeBackgroundColorCommand.SetUp;
begin
  FChangeBackgroundColorCommand := TChangeBackgroundColorCommand.Create;
end;

procedure TestTChangeBackgroundColorCommand.TearDown;
begin
  FChangeBackgroundColorCommand.Free;
  FChangeBackgroundColorCommand := nil;
end;

procedure TestTChangeBackgroundColorCommand.TestExecute;
var
  aData: variant;
  aPrimitive: TGraphicPrimitive;
begin
  aData := clBlue;
  aPrimitive := TGraphicPrimitive.Create(nil);
  aPrimitive.BackgroundColor := clRed;
  try
    FChangeBackgroundColorCommand.Execute(aPrimitive, aData);
    Check( aPrimitive.BackgroundColor = clBlue );
  finally
    aPrimitive.Free;
  end;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTBaseDrawingCommand.Suite);
  RegisterTest(TestTChangeBackgroundColorCommand.Suite);
end.

